version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1